app:
  name: bitcoin-django-backend
  valueStream: hackathon
  namespace: bitcoin
  environment: prd
  default_tags:
    tier: backend
    squad: bitcoin
    product: bitcoin
  secretStore:
    enabled: true
    keys:
      - secretName: global-secret-newrelic-license-key
        envName: NEW_RELIC_LICENSE_KEY
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::200185864022:role/bitcoin-django-backend-role-application
  replicas: 2
  image:
    repository: 410950410321.dkr.ecr.us-east-1.amazonaws.com/bitcoin-django-backend
  service:
    enabled: true
  port: 3000
  ingress:
    scope: public
    wafArn: ''
  hpa:
    enable: false
  resources:
    cpu: 80m
    memory: 80Mi
  probe:
    path: /healthcheck
    port: http
    initialDelaySeconds: 15
    timeoutSeconds: 3
    periodSeconds: 15
  env:
    - name: NEW_RELIC_CONFIG_FILE
      value: ./newrelic.ini
    - name: SECRET_KEY
      value: '123456'
    - name: PYTHONPATH
      value: .
    - name: PYTHONUNBUFFERED
      value: '1'
    - name: PYTHONDONTWRITEBYTECODE
      value: '1'
    - name: POETRY_VIRTUALENVS_CREATE
      value: 'false'
    - name: LOG_LEVEL_ENABLED
      value: ERROR
    - name: DATABASE
      value: bitcoin
    - name: HOST
      valueFrom:
        secretKeyRef:
          name: bitcoin-django-backend-conn-string
          key: endpoint
    - name: USER
      valueFrom:
        secretKeyRef:
          name: bitcoin-django-backend-conn-string
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: bitcoin-django-backend-conn-string
          key: password
    - name: PORT
      valueFrom:
        secretKeyRef:
          name: bitcoin-django-backend-conn-string
          key: port
